CREATE TABLE USERS(
	USER_ID INT NOT NULL AUTO_INCREMENT,
    LOGIN_ID VARCHAR(50) NOT NULL UNIQUE,
    USER_PW VARCHAR(15) NOT NULL,
    USER_NAME VARCHAR(10) NOT NULL,
    PHONE VARCHAR(20) UNIQUE,
    EMAIL VARCHAR(255) UNIQUE,
    AUTH ENUM('ADMIN', 'CONSUMER') NOT NULL DEFAULT 'CONSUMER',
    PRIMARY KEY (USER_ID)
);

CREATE TABLE ADDRESS (
    ADD_ID INT NOT NULL AUTO_INCREMENT,
    ADDRESS VARCHAR(255),
    ADD_NAME VARCHAR(20),
    USER_ID INT NOT NULL,
    PRIMARY KEY (ADD_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);


CREATE TABLE CROP (
	CROP_ID INT NOT NULL AUTO_INCREMENT,
    CROP_NAME VARCHAR(20) NOT NULL,
    REG_DATE DATE NOT NULL DEFAULT (CURRENT_DATE),
    STATUS TINYINT DEFAULT 0,
    GROWTH_TIME INT,
    QUANTITY INT,
    UNIT_NAME VARCHAR(10),
    ELAPSED_TICK INT NOT NULL DEFAULT 0,
    PRIMARY KEY (CROP_ID)
);
select * from crop;

CREATE TABLE INVENTORY (
    STOR_ID INT NOT NULL AUTO_INCREMENT,
    AMOUNT INT NOT NULL DEFAULT 0,
    STATUS TINYINT DEFAULT 0,
    CROP_ID INT NOT NULL,   
    PRIMARY KEY (STOR_ID),
    FOREIGN KEY (CROP_ID) REFERENCES CROP(CROP_ID)
);

select * from inventory;
CREATE TABLE SHOP (
    ITEM_ID INT NOT NULL AUTO_INCREMENT,
    ITEM_NAME VARCHAR(10),
    PRICE INT NOT NULL DEFAULT 0,
    STOR_ID INT NOT NULL,
    PRIMARY KEY (ITEM_ID),
    FOREIGN KEY (STOR_ID) REFERENCES INVENTORY(STOR_ID)
);

CREATE TABLE CART (
    USER_ID INT NOT NULL,
    ITEM_ID INT NOT NULL,
    AMOUNT INT NOT NULL DEFAULT 1,
    PRIMARY KEY (USER_ID, ITEM_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES SHOP(ITEM_ID)
);

CREATE TABLE ORDERS (
    ORDER_ID INT NOT NULL AUTO_INCREMENT,
    STATUS ENUM('주문 대기', '배송 중') NOT NULL,
    ADDRESS VARCHAR(255),
    PHONE VARCHAR(15),
    USER_ID INT NOT NULL,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE ORDER_AMOUNT (
    ORDER_ID INT NOT NULL,
    ITEM_ID INT NOT NULL,
    AMOUNT INT NOT NULL DEFAULT 1,
    UNIT_PRICE INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ORDER_ID, ITEM_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES SHOP(ITEM_ID)
);
